//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessUser
    {
        public int BusinessID { get; set; }
        public int UserId { get; set; }
        public short UserRolesId { get; set; }
        public string GroupName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedByUserId { get; set; }
        public bool IsActive { get; set; }
        public string UserGuid { get; set; }
    
        public virtual Mst_UserRoles Mst_UserRoles { get; set; }
        public virtual BusinessRegistration BusinessRegistration { get; set; }
        public virtual User User { get; set; }
    }
}
