//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessRegistration
    {
        public BusinessRegistration()
        {
            this.Documents = new HashSet<Document>();
            this.EmployeeLeaveBillingDetails = new HashSet<EmployeeLeaveBillingDetail>();
            this.EmployeeLeaves = new HashSet<EmployeeLeaf>();
            this.EmployeePayrolls = new HashSet<EmployeePayroll>();
            this.EmployeesTimesheets = new HashSet<EmployeesTimesheet>();
            this.UserCustomers = new HashSet<UserCustomer>();
            this.UserEmployees = new HashSet<UserEmployee>();
            this.UserVendors = new HashSet<UserVendor>();
            this.BusinessBranches = new HashSet<BusinessBranch>();
            this.Assets = new HashSet<Asset>();
            this.Assets1 = new HashSet<Asset>();
            this.UMst_BusinessPreferences = new HashSet<UMst_BusinessPreferences>();
            this.BusinessStatus = new HashSet<BusinessStatu>();
            this.BusinessUsers = new HashSet<BusinessUser>();
            this.EmployeeAssets = new HashSet<EmployeeAsset>();
            this.Estimates = new HashSet<Estimate>();
            this.Expenses = new HashSet<Expens>();
            this.IPBlockers = new HashSet<IPBlocker>();
            this.Journals = new HashSet<Journal>();
            this.Payments = new HashSet<Payment>();
            this.PurchaseInvoices = new HashSet<PurchaseInvoice>();
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            this.Receipts = new HashSet<Receipt>();
            this.Payments1 = new HashSet<Payment>();
            this.UMst_TaxDetails = new HashSet<UMst_TaxDetails>();
            this.UMst_AssetType = new HashSet<UMst_AssetType>();
            this.UMst_BusinessItems = new HashSet<UMst_BusinessItems>();
            this.UMst_UserAccounts = new HashSet<UMst_UserAccounts>();
            this.UMst_UserCustomFields = new HashSet<UMst_UserCustomFields>();
            this.UMst_UserParentAccounts = new HashSet<UMst_UserParentAccounts>();
            this.UserBankAccounts = new HashSet<UserBankAccount>();
            this.UMst_UserCustomizeFields = new HashSet<UMst_UserCustomizeFields>();
            this.UMst_UserGreetingEmails = new HashSet<UMst_UserGreetingEmails>();
            this.UserPaymentDetails = new HashSet<UserPaymentDetail>();
        }
    
        public int BusinessID { get; set; }
        public string BusinessName { get; set; }
        public Nullable<short> BusinessTypeId { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<short> CountryId { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public Nullable<int> Licences { get; set; }
        public string DUNS_ { get; set; }
        public string DBA { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedByUserId { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CountyId { get; set; }
    
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<EmployeeLeaveBillingDetail> EmployeeLeaveBillingDetails { get; set; }
        public virtual ICollection<EmployeeLeaf> EmployeeLeaves { get; set; }
        public virtual ICollection<EmployeePayroll> EmployeePayrolls { get; set; }
        public virtual ICollection<EmployeesTimesheet> EmployeesTimesheets { get; set; }
        public virtual ICollection<UserCustomer> UserCustomers { get; set; }
        public virtual ICollection<UserEmployee> UserEmployees { get; set; }
        public virtual ICollection<UserVendor> UserVendors { get; set; }
        public virtual Mst_BusinessType Mst_BusinessType { get; set; }
        public virtual Mst_Cities Mst_Cities { get; set; }
        public virtual Mst_Counties Mst_Counties { get; set; }
        public virtual Mst_Countries Mst_Countries { get; set; }
        public virtual Mst_States Mst_States { get; set; }
        public virtual ICollection<BusinessBranch> BusinessBranches { get; set; }
        public virtual ICollection<Asset> Assets { get; set; }
        public virtual ICollection<Asset> Assets1 { get; set; }
        public virtual ICollection<UMst_BusinessPreferences> UMst_BusinessPreferences { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<BusinessStatu> BusinessStatus { get; set; }
        public virtual ICollection<BusinessUser> BusinessUsers { get; set; }
        public virtual ICollection<EmployeeAsset> EmployeeAssets { get; set; }
        public virtual ICollection<Estimate> Estimates { get; set; }
        public virtual ICollection<Expens> Expenses { get; set; }
        public virtual ICollection<IPBlocker> IPBlockers { get; set; }
        public virtual ICollection<Journal> Journals { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<PurchaseInvoice> PurchaseInvoices { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual ICollection<Receipt> Receipts { get; set; }
        public virtual ICollection<Payment> Payments1 { get; set; }
        public virtual ICollection<UMst_TaxDetails> UMst_TaxDetails { get; set; }
        public virtual ICollection<UMst_AssetType> UMst_AssetType { get; set; }
        public virtual ICollection<UMst_BusinessItems> UMst_BusinessItems { get; set; }
        public virtual ICollection<UMst_UserAccounts> UMst_UserAccounts { get; set; }
        public virtual ICollection<UMst_UserCustomFields> UMst_UserCustomFields { get; set; }
        public virtual ICollection<UMst_UserParentAccounts> UMst_UserParentAccounts { get; set; }
        public virtual ICollection<UserBankAccount> UserBankAccounts { get; set; }
        public virtual ICollection<UMst_UserCustomizeFields> UMst_UserCustomizeFields { get; set; }
        public virtual ICollection<UMst_UserGreetingEmails> UMst_UserGreetingEmails { get; set; }
        public virtual ICollection<UserPaymentDetail> UserPaymentDetails { get; set; }
    }
}
