//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeBankDetail
    {
        public long EmployeesBankId { get; set; }
        public long UserEmployeeId { get; set; }
        public string AccountNumber { get; set; }
        public string BankName { get; set; }
        public Nullable<short> BankAccountTypeId { get; set; }
        public string Routing { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<short> CountryId { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedByUserId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CountyId { get; set; }
    
        public virtual Mst_BankAccountTypes Mst_BankAccountTypes { get; set; }
        public virtual Mst_Cities Mst_Cities { get; set; }
        public virtual Mst_Counties Mst_Counties { get; set; }
        public virtual Mst_Countries Mst_Countries { get; set; }
        public virtual Mst_States Mst_States { get; set; }
        public virtual UserEmployee UserEmployee { get; set; }
    }
}
