//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estimate
    {
        public Estimate()
        {
            this.EstimatesDetails = new HashSet<EstimatesDetail>();
        }
    
        public long EstimatesId { get; set; }
        public int BusinessID { get; set; }
        public long UserCustomerId { get; set; }
        public Nullable<System.DateTime> EstimateDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string CustomField1 { get; set; }
        public string CustomField2 { get; set; }
        public string CustomField3 { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedByUserId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public bool IsActive { get; set; }
        public string EstimateNum { get; set; }
        public Nullable<short> StatusId { get; set; }
    
        public virtual UserCustomer UserCustomer { get; set; }
        public virtual Mst_Invoicestatus Mst_Invoicestatus { get; set; }
        public virtual BusinessRegistration BusinessRegistration { get; set; }
        public virtual ICollection<EstimatesDetail> EstimatesDetails { get; set; }
    }
}
