//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expens
    {
        public long ExpensesId { get; set; }
        public int BusinessID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public short PaymentTypesId { get; set; }
        public string PayeeName { get; set; }
        public string PayeeType { get; set; }
        public long UserAccountsId { get; set; }
        public long ItemId { get; set; }
        public short ItemTypeId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<long> PurchaseInvoiceId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedByUserId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public bool IsInvoice { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Mst_ItemTypes Mst_ItemTypes { get; set; }
        public virtual Mst_PaymentTypes Mst_PaymentTypes { get; set; }
        public virtual BusinessRegistration BusinessRegistration { get; set; }
        public virtual PurchaseInvoice PurchaseInvoice { get; set; }
        public virtual UMst_UserAccounts UMst_UserAccounts { get; set; }
    }
}
