//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_AccountTypes
    {
        public Mst_AccountTypes()
        {
            this.Mst_AccountSubTypes = new HashSet<Mst_AccountSubTypes>();
        }
    
        public short AccountTypesId { get; set; }
        public string AccountDesc { get; set; }
        public Nullable<short> ParentAccountTypesId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<Mst_AccountSubTypes> Mst_AccountSubTypes { get; set; }
    }
}
