//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_PreferenceValues
    {
        public Mst_PreferenceValues()
        {
            this.UMst_BusinessPreferences = new HashSet<UMst_BusinessPreferences>();
        }
    
        public short PreferenceValuesId { get; set; }
        public Nullable<short> PreferenceFieldsId { get; set; }
        public string PreferenceValue { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Mst_PreferenceFields Mst_PreferenceFields { get; set; }
        public virtual ICollection<UMst_BusinessPreferences> UMst_BusinessPreferences { get; set; }
    }
}
