//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_BusinessType
    {
        public Mst_BusinessType()
        {
            this.UserCustomers = new HashSet<UserCustomer>();
            this.BusinessRegistrations = new HashSet<BusinessRegistration>();
        }
    
        public short BusinessTypeId { get; set; }
        public string BusinessType { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<UserCustomer> UserCustomers { get; set; }
        public virtual ICollection<BusinessRegistration> BusinessRegistrations { get; set; }
    }
}
