//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_BusinessStatus
    {
        public Mst_BusinessStatus()
        {
            this.BusinessStatus1 = new HashSet<BusinessStatu>();
        }
    
        public short BusinessStatusId { get; set; }
        public string BusinessStatus { get; set; }
        public string BusinessStatusDescription { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<BusinessStatu> BusinessStatus1 { get; set; }
    }
}
