//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_AccountUserTypes
    {
        public Mst_AccountUserTypes()
        {
            this.UMst_UserAccounts = new HashSet<UMst_UserAccounts>();
        }
    
        public short AccountUserTypeId { get; set; }
        public string AccountUserType { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<UMst_UserAccounts> UMst_UserAccounts { get; set; }
    }
}
