//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_AssetDisposition
    {
        public Mst_AssetDisposition()
        {
            this.Assets = new HashSet<Asset>();
        }
    
        public short AssetDispositionId { get; set; }
        public string AssetDispositionName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<Asset> Assets { get; set; }
    }
}
