//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_Countries
    {
        public Mst_Countries()
        {
            this.CustomersAddresses = new HashSet<CustomersAddress>();
            this.EmployeeBankDetails = new HashSet<EmployeeBankDetail>();
            this.UserEmployees = new HashSet<UserEmployee>();
            this.VendorsAddresses = new HashSet<VendorsAddress>();
            this.BusinessRegistrations = new HashSet<BusinessRegistration>();
            this.Mst_States = new HashSet<Mst_States>();
        }
    
        public short CountryId { get; set; }
        public string Country { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<CustomersAddress> CustomersAddresses { get; set; }
        public virtual ICollection<EmployeeBankDetail> EmployeeBankDetails { get; set; }
        public virtual ICollection<UserEmployee> UserEmployees { get; set; }
        public virtual ICollection<VendorsAddress> VendorsAddresses { get; set; }
        public virtual ICollection<BusinessRegistration> BusinessRegistrations { get; set; }
        public virtual ICollection<Mst_States> Mst_States { get; set; }
    }
}
