//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_CustomersRename
    {
        public Mst_CustomersRename()
        {
            this.UMst_UserCustomizeFields = new HashSet<UMst_UserCustomizeFields>();
        }
    
        public short CustomersRenameId { get; set; }
        public string CustomersRename { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<UMst_UserCustomizeFields> UMst_UserCustomizeFields { get; set; }
    }
}
