//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_InvoiceDueTerm
    {
        public Mst_InvoiceDueTerm()
        {
            this.PurchaseInvoices = new HashSet<PurchaseInvoice>();
        }
    
        public short DueTermId { get; set; }
        public string Term { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<PurchaseInvoice> PurchaseInvoices { get; set; }
    }
}
