//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_SignupPricing
    {
        public Mst_SignupPricing()
        {
            this.BusinessStatus = new HashSet<BusinessStatu>();
        }
    
        public short SignupPricingId { get; set; }
        public string SignupType { get; set; }
        public string SignupDescription { get; set; }
        public Nullable<int> LicencesNum { get; set; }
        public Nullable<decimal> AmountPerMonth { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<BusinessStatu> BusinessStatus { get; set; }
    }
}
