//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_BankAccountTypes
    {
        public Mst_BankAccountTypes()
        {
            this.EmployeeBankDetails = new HashSet<EmployeeBankDetail>();
            this.UserBankAccounts = new HashSet<UserBankAccount>();
        }
    
        public short BankAccountTypeId { get; set; }
        public string AccountTypeDesc { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<EmployeeBankDetail> EmployeeBankDetails { get; set; }
        public virtual ICollection<UserBankAccount> UserBankAccounts { get; set; }
    }
}
