//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_ItemTypes
    {
        public Mst_ItemTypes()
        {
            this.EstimatesDetails = new HashSet<EstimatesDetail>();
            this.Expenses = new HashSet<Expens>();
            this.SalesInvoiceDetails = new HashSet<SalesInvoiceDetail>();
            this.UMst_BusinessItems = new HashSet<UMst_BusinessItems>();
        }
    
        public short ItemTypeId { get; set; }
        public string ItemTypeDesc { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<EstimatesDetail> EstimatesDetails { get; set; }
        public virtual ICollection<Expens> Expenses { get; set; }
        public virtual ICollection<SalesInvoiceDetail> SalesInvoiceDetails { get; set; }
        public virtual ICollection<UMst_BusinessItems> UMst_BusinessItems { get; set; }
    }
}
