//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_GreetingsList
    {
        public Mst_GreetingsList()
        {
            this.UMst_UserGreetingEmails = new HashSet<UMst_UserGreetingEmails>();
        }
    
        public short GreetingsListId { get; set; }
        public string GreetingName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<UMst_UserGreetingEmails> UMst_UserGreetingEmails { get; set; }
    }
}
