//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_PaymentTypes
    {
        public Mst_PaymentTypes()
        {
            this.EmployeePaymentTypes = new HashSet<EmployeePaymentType>();
            this.UserCustomers = new HashSet<UserCustomer>();
            this.UserVendors = new HashSet<UserVendor>();
            this.Expenses = new HashSet<Expens>();
            this.Payments = new HashSet<Payment>();
            this.PurchaseInvoicePayments = new HashSet<PurchaseInvoicePayment>();
            this.SalesReceipts = new HashSet<SalesReceipt>();
        }
    
        public short PaymentTypesId { get; set; }
        public string PaymentDesc { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<EmployeePaymentType> EmployeePaymentTypes { get; set; }
        public virtual ICollection<UserCustomer> UserCustomers { get; set; }
        public virtual ICollection<UserVendor> UserVendors { get; set; }
        public virtual ICollection<Expens> Expenses { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<PurchaseInvoicePayment> PurchaseInvoicePayments { get; set; }
        public virtual ICollection<SalesReceipt> SalesReceipts { get; set; }
    }
}
