//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_UserType
    {
        public Mst_UserType()
        {
            this.PurchaseInvoicePayments = new HashSet<PurchaseInvoicePayment>();
            this.UserBankAccounts = new HashSet<UserBankAccount>();
        }
    
        public short UserTypeId { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<PurchaseInvoicePayment> PurchaseInvoicePayments { get; set; }
        public virtual ICollection<UserBankAccount> UserBankAccounts { get; set; }
    }
}
