//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_TaxTypes
    {
        public Mst_TaxTypes()
        {
            this.CustomerTaxDetails = new HashSet<CustomerTaxDetail>();
            this.VendorTaxDetails = new HashSet<VendorTaxDetail>();
            this.UMst_TaxDetails = new HashSet<UMst_TaxDetails>();
        }
    
        public short TaxTypesId { get; set; }
        public string TaxName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<CustomerTaxDetail> CustomerTaxDetails { get; set; }
        public virtual ICollection<VendorTaxDetail> VendorTaxDetails { get; set; }
        public virtual ICollection<UMst_TaxDetails> UMst_TaxDetails { get; set; }
    }
}
