//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_UserRoles
    {
        public Mst_UserRoles()
        {
            this.BusinessUsers = new HashSet<BusinessUser>();
        }
    
        public short UserRolesId { get; set; }
        public string UserRoles { get; set; }
        public string UserRolesDescription { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<BusinessUser> BusinessUsers { get; set; }
    }
}
