//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_AddressType
    {
        public Mst_AddressType()
        {
            this.CustomersAddresses = new HashSet<CustomersAddress>();
            this.VendorsAddresses = new HashSet<VendorsAddress>();
        }
    
        public short AddressTypeId { get; set; }
        public string AddressDesc { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<CustomersAddress> CustomersAddresses { get; set; }
        public virtual ICollection<VendorsAddress> VendorsAddresses { get; set; }
    }
}
