//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_States
    {
        public Mst_States()
        {
            this.CustomersAddresses = new HashSet<CustomersAddress>();
            this.EmployeeBankDetails = new HashSet<EmployeeBankDetail>();
            this.UserEmployees = new HashSet<UserEmployee>();
            this.VendorsAddresses = new HashSet<VendorsAddress>();
            this.Mst_Cities = new HashSet<Mst_Cities>();
            this.Mst_Counties = new HashSet<Mst_Counties>();
            this.BusinessRegistrations = new HashSet<BusinessRegistration>();
        }
    
        public int StateId { get; set; }
        public string State { get; set; }
        public short CountryId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<CustomersAddress> CustomersAddresses { get; set; }
        public virtual ICollection<EmployeeBankDetail> EmployeeBankDetails { get; set; }
        public virtual ICollection<UserEmployee> UserEmployees { get; set; }
        public virtual ICollection<VendorsAddress> VendorsAddresses { get; set; }
        public virtual ICollection<Mst_Cities> Mst_Cities { get; set; }
        public virtual ICollection<Mst_Counties> Mst_Counties { get; set; }
        public virtual Mst_Countries Mst_Countries { get; set; }
        public virtual ICollection<BusinessRegistration> BusinessRegistrations { get; set; }
    }
}
