//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public long PaymentsId { get; set; }
        public int BusinessID { get; set; }
        public long UserAccountsId { get; set; }
        public short PaymentTypesId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<long> PaidByEmployeeId { get; set; }
        public string Payee { get; set; }
        public string PayeeType { get; set; }
        public Nullable<long> PurchaseInvoicePaymentId { get; set; }
        public string CardTitle { get; set; }
        public string CheckNum { get; set; }
        public Nullable<long> BankAccountsId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedByUserId { get; set; }
        public bool Verified { get; set; }
        public Nullable<int> BranchId { get; set; }
        public bool IsInvoicePayment { get; set; }
        public bool IsActive { get; set; }
    
        public virtual UserEmployee UserEmployee { get; set; }
        public virtual Mst_PaymentTypes Mst_PaymentTypes { get; set; }
        public virtual BusinessRegistration BusinessRegistration { get; set; }
        public virtual BusinessRegistration BusinessRegistration1 { get; set; }
        public virtual UserBankAccount UserBankAccount { get; set; }
        public virtual PurchaseInvoicePayment PurchaseInvoicePayment { get; set; }
        public virtual UMst_UserAccounts UMst_UserAccounts { get; set; }
    }
}
