//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseInvoiceDetail
    {
        public long PurchaseInvoiceDetailsId { get; set; }
        public Nullable<long> PurchaseInvoiceId { get; set; }
        public long ItemId { get; set; }
        public string Description { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedByUserId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<decimal> TaxPercent { get; set; }
        public Nullable<decimal> Tax { get; set; }
    
        public virtual PurchaseInvoice PurchaseInvoice { get; set; }
        public virtual UMst_BusinessItems UMst_BusinessItems { get; set; }
    }
}
