//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public long ReceiptId { get; set; }
        public int BusinessID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<long> BankAccountsId { get; set; }
        public string ReceiptNum { get; set; }
        public string DepositFrom { get; set; }
        public string DepositerType { get; set; }
        public long UserAccountsId { get; set; }
        public Nullable<long> SalesReceiptId { get; set; }
        public bool IsInvoiceReceipt { get; set; }
        public bool Verified { get; set; }
        public string CustomField1 { get; set; }
        public string CustomField2 { get; set; }
        public string CustomField3 { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedByUserId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual BusinessRegistration BusinessRegistration { get; set; }
        public virtual UserBankAccount UserBankAccount { get; set; }
        public virtual SalesReceipt SalesReceipt { get; set; }
        public virtual UMst_UserAccounts UMst_UserAccounts { get; set; }
    }
}
