//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rpt_Transactions
    {
        public int Id { get; set; }
        public Nullable<int> AccountId { get; set; }
        public string AccountName { get; set; }
        public string Description { get; set; }
        public string Item { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<short> IsCreditor { get; set; }
        public Nullable<long> UserParentAccountsId { get; set; }
    }
}
