//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesReceipt
    {
        public SalesReceipt()
        {
            this.Receipts = new HashSet<Receipt>();
        }
    
        public long SalesReceiptId { get; set; }
        public long SalesInvoiceId { get; set; }
        public string ReceiptNum { get; set; }
        public short PaymentTypesId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<long> UserCustomerId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Description { get; set; }
        public string CustomField1 { get; set; }
        public string CustomField2 { get; set; }
        public string CustomField3 { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedByUserId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Mst_PaymentTypes Mst_PaymentTypes { get; set; }
        public virtual ICollection<Receipt> Receipts { get; set; }
        public virtual SalesInvoice SalesInvoice { get; set; }
    }
}
