//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Serial
    {
        public int SerialID { get; set; }
        public string ColumnName { get; set; }
        public long SerialCurrentNo { get; set; }
        public Nullable<int> BusinessId { get; set; }
        public bool IsActive { get; set; }
    }
}
