//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public long TransactionId { get; set; }
        public int BusinessID { get; set; }
        public long UserAccountsId { get; set; }
        public short TransactionTypeId { get; set; }
        public decimal Debit { get; set; }
        public decimal Credit { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string Narration { get; set; }
        public string VoucherNumber { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<long> ItemId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedByUserId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual UMst_UserAccounts UMst_UserAccounts { get; set; }
    }
}
