//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UMst_AssetType
    {
        public UMst_AssetType()
        {
            this.Assets = new HashSet<Asset>();
        }
    
        public int AssetTypeId { get; set; }
        public string AssetName { get; set; }
        public int BusinessID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedByUserId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual BusinessRegistration BusinessRegistration { get; set; }
        public virtual ICollection<Asset> Assets { get; set; }
    }
}
