//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UMst_BusinessItems
    {
        public UMst_BusinessItems()
        {
            this.PurchaseInvoiceDetails = new HashSet<PurchaseInvoiceDetail>();
            this.PurchaseOrderDetails = new HashSet<PurchaseOrderDetail>();
        }
    
        public long ItemId { get; set; }
        public int BusinessID { get; set; }
        public short ItemTypeId { get; set; }
        public string Title { get; set; }
        public string UniqueId { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<decimal> DiscountPrice { get; set; }
        public Nullable<decimal> PreferredPrice { get; set; }
        public long UserAccountsId { get; set; }
        public Nullable<bool> Taxable { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedByUserId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsPreferredPrice { get; set; }
    
        public virtual Mst_ItemTypes Mst_ItemTypes { get; set; }
        public virtual BusinessRegistration BusinessRegistration { get; set; }
        public virtual ICollection<PurchaseInvoiceDetail> PurchaseInvoiceDetails { get; set; }
        public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
        public virtual UMst_UserAccounts UMst_UserAccounts { get; set; }
    }
}
