//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UMst_UserAccounts
    {
        public UMst_UserAccounts()
        {
            this.UserCustomers = new HashSet<UserCustomer>();
            this.UserVendors = new HashSet<UserVendor>();
            this.UserBankAccounts = new HashSet<UserBankAccount>();
            this.Expenses = new HashSet<Expens>();
            this.Payments = new HashSet<Payment>();
            this.PurchaseInvoicePayments = new HashSet<PurchaseInvoicePayment>();
            this.Receipts = new HashSet<Receipt>();
            this.Transactions = new HashSet<Transaction>();
            this.Journals = new HashSet<Journal>();
            this.UMst_BusinessItems = new HashSet<UMst_BusinessItems>();
        }
    
        public long UserAccountsId { get; set; }
        public int BusinessID { get; set; }
        public Nullable<int> AccountNum { get; set; }
        public string AccountName { get; set; }
        public int UserParentAccountsId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedByUserId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<short> AccountUserTypeId { get; set; }
    
        public virtual ICollection<UserCustomer> UserCustomers { get; set; }
        public virtual ICollection<UserVendor> UserVendors { get; set; }
        public virtual Mst_AccountUserTypes Mst_AccountUserTypes { get; set; }
        public virtual BusinessRegistration BusinessRegistration { get; set; }
        public virtual ICollection<UserBankAccount> UserBankAccounts { get; set; }
        public virtual ICollection<Expens> Expenses { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<PurchaseInvoicePayment> PurchaseInvoicePayments { get; set; }
        public virtual ICollection<Receipt> Receipts { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual ICollection<Journal> Journals { get; set; }
        public virtual ICollection<UMst_BusinessItems> UMst_BusinessItems { get; set; }
        public virtual UMst_UserParentAccounts UMst_UserParentAccounts { get; set; }
    }
}
