//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.BusinessRegistrations = new HashSet<BusinessRegistration>();
            this.BusinessRegistrations1 = new HashSet<BusinessRegistration>();
            this.BusinessUsers = new HashSet<BusinessUser>();
            this.UserLoginDetails = new HashSet<UserLoginDetail>();
        }
    
        public int UserId { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
        public string Email { get; set; }
        public string UserPassword { get; set; }
        public byte[] UserImage { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedByUserId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<BusinessRegistration> BusinessRegistrations { get; set; }
        public virtual ICollection<BusinessRegistration> BusinessRegistrations1 { get; set; }
        public virtual ICollection<BusinessUser> BusinessUsers { get; set; }
        public virtual ICollection<UserLoginDetail> UserLoginDetails { get; set; }
    }
}
