//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserVendor
    {
        public UserVendor()
        {
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            this.VendorsAddresses = new HashSet<VendorsAddress>();
            this.VendorTaxDetails = new HashSet<VendorTaxDetail>();
        }
    
        public long UserVendorId { get; set; }
        public int BusinessID { get; set; }
        public string CompanyName { get; set; }
        public string VendorFirstName { get; set; }
        public string VendorLastName { get; set; }
        public string Title { get; set; }
        public string Website { get; set; }
        public Nullable<short> PaymentTypesId { get; set; }
        public string CreditCardToken { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedByUserId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<short> VendorTypeId { get; set; }
        public Nullable<bool> IsTaxable { get; set; }
        public Nullable<long> UserAccountsId { get; set; }
    
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual BusinessRegistration BusinessRegistration { get; set; }
        public virtual Mst_PaymentTypes Mst_PaymentTypes { get; set; }
        public virtual Mst_VendorType Mst_VendorType { get; set; }
        public virtual UMst_UserAccounts UMst_UserAccounts { get; set; }
        public virtual ICollection<VendorsAddress> VendorsAddresses { get; set; }
        public virtual ICollection<VendorTaxDetail> VendorTaxDetails { get; set; }
    }
}
