//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBankAccount
    {
        public UserBankAccount()
        {
            this.Payments = new HashSet<Payment>();
            this.Receipts = new HashSet<Receipt>();
        }
    
        public long BankAccountsId { get; set; }
        public int BusinessID { get; set; }
        public string BankName { get; set; }
        public short BankAccountTypeId { get; set; }
        public long UserId { get; set; }
        public short UserTypeId { get; set; }
        public string AccountNum { get; set; }
        public decimal OpeningBalance { get; set; }
        public string AccountHolder1Name { get; set; }
        public string AccountHolder2Name { get; set; }
        public string AccountHolder3Name { get; set; }
        public string SwiftCode { get; set; }
        public string RountingNum { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedByUserId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<long> UserAccountsId { get; set; }
    
        public virtual Mst_BankAccountTypes Mst_BankAccountTypes { get; set; }
        public virtual Mst_UserType Mst_UserType { get; set; }
        public virtual BusinessRegistration BusinessRegistration { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<Receipt> Receipts { get; set; }
        public virtual UMst_UserAccounts UMst_UserAccounts { get; set; }
    }
}
