//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCustomer
    {
        public UserCustomer()
        {
            this.CustomersAddresses = new HashSet<CustomersAddress>();
            this.CustomerTaxDetails = new HashSet<CustomerTaxDetail>();
            this.Estimates = new HashSet<Estimate>();
            this.SalesInvoices = new HashSet<SalesInvoice>();
        }
    
        public long UserCustomerId { get; set; }
        public int BusinessID { get; set; }
        public string CompanyName { get; set; }
        public string CustomerFirstName { get; set; }
        public string CustomerLastName { get; set; }
        public Nullable<short> BusinessTypeId { get; set; }
        public Nullable<bool> IsProfitType { get; set; }
        public string Website { get; set; }
        public Nullable<short> CreditPeriodTypeId { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public Nullable<short> PaymentTypesId { get; set; }
        public string CreditCardToken { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedByUserId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<long> UserAccountsId { get; set; }
        public Nullable<bool> IsTaxable { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<CustomersAddress> CustomersAddresses { get; set; }
        public virtual ICollection<CustomerTaxDetail> CustomerTaxDetails { get; set; }
        public virtual ICollection<Estimate> Estimates { get; set; }
        public virtual ICollection<SalesInvoice> SalesInvoices { get; set; }
        public virtual BusinessRegistration BusinessRegistration { get; set; }
        public virtual Mst_BusinessType Mst_BusinessType { get; set; }
        public virtual Mst_CreditPeriodTypes Mst_CreditPeriodTypes { get; set; }
        public virtual Mst_PaymentTypes Mst_PaymentTypes { get; set; }
        public virtual UMst_UserAccounts UMst_UserAccounts { get; set; }
    }
}
