//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLoginDetail
    {
        public int UserId { get; set; }
        public System.DateTime LoginStartTime { get; set; }
        public System.DateTime LoginEndTime { get; set; }
    
        public virtual User User { get; set; }
    }
}
